### ISSUE TITLE
a lot of templates are broken

### ISSUE THREAD

**Issue by diffweb** [topscoder/nuclei-wordfence-cve#9]
for example

```
nuclei -t wordpress/nuclei-wordfence-cve/nuclei-templates/cve-less/unknown/zoner-d41d8cd98f00b204e9800998ecf8427e.yaml  -validate


                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.8

                projectdiscovery.io

[ERR] Error occurred loading template wordpress/nuclei-wordfence-cve/nuclei-templates/cve-less/unknown/zoner-d41d8cd98f00b204e9800998ecf8427e.yaml: Could not load template wordpress/nuclei-wordfence-cve/nuclei-templates/cve-less/unknown/zoner-d41d8cd98f00b204e9800998ecf8427e.yaml: yaml: line 6: did not find expected key
[FTL] Could not validate templates: errors occured during template validation

```

https://github.com/topscoder/nuclei-wordfence-cve/blob/main/nuclei-templates/cve-less/unknown/zoner-d41d8cd98f00b204e9800998ecf8427e.yaml

![image](https://github.com/topscoder/nuclei-wordfence-cve/assets/30118052/807c7347-48ce-438f-a094-0f41d6220f7d)

the description should be

```
  description:  The "Zoner - Real Estate WordPress Theme" theme for WordPress is vulnerable to Cross-Site Scripting via the 'Address' field in versions before 4.2 due to insufficient input sanitization and output escaping. This makes it possible for attackers to inject arbitrary web scripts that execute in a victim's browser.
```

not 
```
  description: "The "Zoner - Real Estate WordPress Theme" theme for WordPress is vulnerable to Cross-Site Scripting via the 'Address' field in versions before 4.2 due to insufficient input sanitization and output escaping. This makes it possible for attackers to inject arbitrary web scripts that execute in a victim's browser."
```

**Comment by diffweb** [comment]
![image](https://github.com/topscoder/nuclei-wordfence-cve/assets/30118052/85819b7c-22f4-46ff-aef7-9d1bf4b3fab7)


a lot of template should be fixed

**Comment by topscoder** [comment]
It unfortunately is not as easy as it seems. 

This line for example is invalid without enclosing quotes:

`description: The following plugins and themes for WordPress are vulnerable to arbitrary option deletion and user data manipulation: Theme Blvd Shortcodes plugin <= 1.5.2 , Theme Blvd Widget Areas plugin < = 1.2.2, Theme Blvd Layout Builder plugin <= 2.0.1, Theme Blvd Sliders plugin <= 1.2.3, WP Jump Start theme <= 1.2.4, Alyeska theme <= 3.1.4, Akita theme <= 2.1.4, Arcadian Responsive theme <= 2.0.5, Swagger theme <= 2.1.4, Commodore theme <= 3.0.2, and Barely Corporate theme <= 4.1.4. This is due to missing authorization on the themeblvd_clear_options() and themeblvd_disable_nag() functions called via 'admin_init' hooks. This makes it possible for unauthenticated attackers to delete any option from the 'wp_options' table and edit any of their user metadata to 'true.'`

**Comment by diffweb** [comment]
yeah , 

I think it can be done with escape

**Comment by topscoder** [comment]
![Scherm­afbeelding 2023-07-22 om 12 28 12](https://github.com/topscoder/nuclei-wordfence-cve/assets/86197446/7351b8e5-3be7-4774-850d-9a51fbb8a7b5)

Fixed ✅
